### ISSUE TITLE
uhm

### ISSUE THREAD

**Issue by cloutjs** [Ransomwarehelp/bitcoin-wallet-miner#1]
please don’t tell me you made ransom ware with my script? you even copied my repos description lol. we on github why you uploading exe files?

**Comment by Hail2Hydra** [comment]
@cloutjs Go Look at his others its disgusting ....

sadly he probably infected a few users that dont scan before they Run anything from anywhere ... R.I.P. x_x

**Comment by Hail2Hydra** [comment]
![unnamed](https://user-images.githubusercontent.com/83504580/181860364-cc960aeb-0986-41d0-83e4-93b1f3b233cf.png)
